"""Render a run's queue handoff as readable markdown.

`07_enqueue/enqueue.jsonl` is what a consuming knowledge base actually reads --
one idempotent event per approved candidate. It is JSONL because that is what
the consumer wants; this is for reading it.

    python demo/real-runs/render.py demo/real-runs/<run-folder>

Writes `enqueue.md` beside the workspace, NOT inside `runs/`, so the artifact
tree stays exactly what the pipeline wrote. This file is a demo reading aid and
nothing in the pipeline produces or consumes it.

Everything rendered comes from enqueue.jsonl. Nothing is added from elsewhere,
so the markdown cannot say more than the handoff itself does.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path


def _only_run(workspace: Path) -> Path:
    runs = sorted(p for p in (workspace / "runs").iterdir() if p.is_dir())
    if len(runs) != 1:
        raise SystemExit(f"{workspace}: expected exactly one run, found {len(runs)}")
    return runs[0]


def render(workspace: Path) -> str:
    run_dir = _only_run(workspace)
    path = run_dir / "07_enqueue" / "enqueue.jsonl"
    if not path.exists():
        raise SystemExit(f"{run_dir}: no 07_enqueue/enqueue.jsonl -- run did not reach pass 6")
    events = [json.loads(l) for l in path.read_text().splitlines() if l.strip()]

    out = [
        f"# {workspace.name} — queue handoff",
        "",
        f"Markdown rendering of `runs/{run_dir.name}/07_enqueue/enqueue.jsonl`, the file a "
        "consuming knowledge base reads. One event per approved candidate. Generated by "
        "`render.py`; a demo reading aid, not a pipeline artifact.",
        "",
        f"**{len(events)} queue event{'s' if len(events) != 1 else ''}** "
        f"· run `{events[0]['run_id']}` · target `{events[0]['target_engine']}` "
        f"· schema `{events[0]['schema_version']}`",
        "",
    ]

    for i, e in enumerate(events, 1):
        p = e["payload"]
        out += [
            "---",
            "",
            f"## {i}. {p['title']}",
            "",
            f"`{e['operation']}` · knowledge state **{p['knowledge_state']}** "
            f"· status `{e['status']}` · candidate `{e['candidate_id']}` v{e['candidate_version']}",
            "",
            f"**Slug** `{p['slug']}`",
            "",
            "### Summary",
            "",
            p["summary"],
            "",
            f"### Assertions ({len(p['assertions'])})",
            "",
        ]
        for n, a in enumerate(p["assertions"], 1):
            backing = ", ".join(f"`{x}`" for x in a.get("assessment_ids", [])) or "—"
            out += [f"{n}. {a['text']}", "", f"   *backed by* {backing}", ""]

        if p.get("related_topics"):
            out += ["### Related topics", "",
                    ", ".join(f"`{t}`" for t in p["related_topics"]), ""]
        if p.get("labels"):
            out += ["### Labels", ""] + [f"- {x}" for x in p["labels"]] + [""]

        out += [
            f"### Source units ({len(p['source_unit_ids'])})", "",
            "\n".join(f"- `{u}`" for u in p["source_unit_ids"]), "",
            "### Traceability", "",
            f"- idempotency key `{e['idempotency_key']}`",
            f"- queue event `{e['queue_event_id']}`",
            f"- audits {', '.join(f'`{a}`' for a in e.get('audit_ids', [])) or '—'}",
            "",
            "Provenance chain recorded on the event:", "",
        ]
        out += [f"- `{k}` → `{v}`" for k, v in sorted(e["provenance_chain"].items())]
        out += [""]

    return "\n".join(out)


if __name__ == "__main__":
    for arg in sys.argv[1:]:
        path = Path(arg)
        (path / "enqueue.md").write_text(render(path))
        print("wrote", path / "enqueue.md")
